name: cleanliness
on:
  push:
    branches: ["*"]
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'release**'
      - 'main'

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup env
        uses: ./.github/actions/build_env

      - name: format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --tests -- -D warnings