name: test sccache

on:
  push:
    branches:
      - 'debug-ci'
env:
  LIBRA_CI: 1
  MODE_0L: "TESTNET"

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    # permissions: write-all
    steps:
    # # NOTE: for debugging CI this allow shell access to github runner. Will print out tmate.io terminal url
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     detached: true
    #   timeout-minutes: 15

    - uses: actions/checkout@v3
    - name: setup env
      uses: ./.github/actions/build_env

    - name: enable sccache
      uses: 0o-de-lally/sccache-action@main

    - name: cargo registry
      run: cargo update -p diem

    - name: quick test serde
      run: cargo c -p serde_json


