name: test sccache

on:
  push:
    branches:
      - 'debug-ci'
env:
  DIEM_FORGE_NODE_BIN_PATH: ${{github.workspace}}/diem-node
  LIBRA_CI: 1
  MODE_0L: "TESTNET"

jobs:
  # preheat-cache:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: setup env
  #     uses: ./.github/actions/build_env

  #   - name: enable sccache
  #     uses: 0o-de-lally/sccache-action@local

  #   - name: build framework
  #     working-directory: ./framework
  #     run: cargo check --tests

  # build-framework:
  #   runs-on: ubuntu-latest
  #   needs: preheat-cache
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: setup env
  #     uses: ./.github/actions/build_env

  #   - name: enable sccache
  #     uses: 0o-de-lally/sccache-action@local

  #   - name: build framework
  #     working-directory: ./framework
  #     run: cargo r release

  rust-tests:
    runs-on: ubuntu-latest
    # needs: build-framework
    steps:
    # # NOTE: for debugging CI this allow shell access to github runner. Will print out tmate.io terminal url
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     detached: true
    #   timeout-minutes: 15

    - uses: actions/checkout@v3
    - name: setup env
      uses: ./.github/actions/build_env

    - name: install diem-node (for smoke tests)
      run: >
        wget -O $DIEM_FORGE_NODE_BIN_PATH https://github.com/0LNetworkCommunity/diem/releases/latest/download/diem-node &&
        sudo chmod 755 $DIEM_FORGE_NODE_BIN_PATH &&
        echo $DIEM_FORGE_NODE_BIN_PATH &&
        ls -l $DIEM_FORGE_NODE_BIN_PATH


    - name: enable sccache
      uses: 0o-de-lally/sccache-action@local

    - name: build framework
      working-directory: ./framework
      run: cargo r release

    - name: all tests
      run: cargo test




